# Site settings
## Change the values as needed.
title: OkGNow
email: okggnow@gmail.com
description: "A Google Fans Blog."
keywords: "jekyll, Google, material, Android"
#url: "http://okgnow.com.br/" # the base hostname & protocol for your site
url: "http://okgnow.com.br/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: brijeshb42
  twitter: brijeshb42
  email: brijeshb42@gmail.com
  github: okgnow/okgnow/
exclude:
  - bower_components
  - README.md
full_name: Brijesh

##set this to enable disqus commenting
disqus: okgnow

##set this to enable google analytics
ga_id: UA-45575876-4
ga_domain: okgnow.com.br
