# Site settings
## Change the values as needed.
title: OkGNow
email: okggnow@gmail.com
description: "A Google Fans Blog."
keywords: "jekyll, Google, material, Android"
#url: "http://okgnow.com.br/" # the base hostname & protocol for your site
url: "http://okgnow.com.br/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  googleplus: 108861196397046400224/108861196397046400224?pageId=108861196397046400224
  youtube: channel/UCd6q8UzDJ0aU2w04_L6RdAA
  facebook: okgnow
  twitter: okggnow
  email: okggnow@gmail.com
  github: okgnow
exclude:
  - bower_components
  - README.md
authors:
  Rychillie:
    name: Rychillie Umpierre de Oliveira
    display_name: Rychillie
    gravatar: 7bde70cef21504f784f19184a4f13153
    email: rychillie@hotmail.com
    web: http://rychillie.github.com
    twitter: @rychillie
    github: rychillie

##set this to enable disqus commenting
disqus: okgnow

##set this to enable google analytics
ga_id: UA-45575876-3
ga_domain: okgnow.com.br
